package VetApp.GUI;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import API.*;
import DatabaseSystems.DatabaseManager;

/**
 *
 * @author Jessica
 */
public class vetPet extends javax.swing.JFrame {

        DateFormat dateFormat = new SimpleDateFormat("MM/dd/YY");
        Date date = new Date();
        Calendar cal = Calendar.getInstance();
        DefaultTableModel model;

        /**
         * Creates new form vetEmpl
         */
        public vetPet() {
                initComponents();

                model = (DefaultTableModel) petTable.getModel();
                dateTxt.setText(" " + dateFormat.format(date));

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                bBack = new javax.swing.JButton();
                jPanel1 = new javax.swing.JPanel();
                bdayL = new javax.swing.JLabel();
                nameL = new javax.swing.JLabel();
                speciesL = new javax.swing.JLabel();
                breedL = new javax.swing.JLabel();
                bdayTxt = new javax.swing.JTextField();
                nameTxt = new javax.swing.JTextField();
                speciesTxt = new javax.swing.JTextField();
                breedTxt = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                petTable = new javax.swing.JTable();
                bAdd = new javax.swing.JButton();
                bDelete = new javax.swing.JButton();
                bUpdate = new javax.swing.JButton();
                genderTxt = new javax.swing.JTextField();
                genderL = new javax.swing.JLabel();
                noteL = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                noteTxt = new javax.swing.JTextArea();
                dateL = new javax.swing.JLabel();
                dateTxt = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Employee Management");

                bBack.setText("BACK");
                bBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bBackActionPerformed(evt);
                        }
                });

                jPanel1.setBackground(new java.awt.Color(167, 231, 225));

                bdayL.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                bdayL.setText("Birth Day:");

                nameL.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                nameL.setText("NAME:");

                speciesL.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                speciesL.setText("Species:");

                breedL.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                breedL.setText("Breed:");

                jLabel1.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
                jLabel1.setText("Pet");

                jLabel2.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
                jLabel2.setText("Management");

                petTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

                }, new String[] { "NAME", "SPECIES", "BREED", "B-DAY", "GENDER" }) {
                        boolean[] canEdit = new boolean[] { false, false, false, false, false };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                petTable.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                petTableMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(petTable);
                if (petTable.getColumnModel().getColumnCount() > 0) {
                        petTable.getColumnModel().getColumn(0).setResizable(false);
                        petTable.getColumnModel().getColumn(1).setResizable(false);
                        petTable.getColumnModel().getColumn(2).setResizable(false);
                        petTable.getColumnModel().getColumn(3).setResizable(false);
                        petTable.getColumnModel().getColumn(4).setResizable(false);
                }

                bAdd.setText("ADD");
                bAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bAddActionPerformed(evt);
                        }
                });

                bDelete.setText("DELETE");
                bDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bDeleteActionPerformed(evt);
                        }
                });

                bUpdate.setText("UPDATE");
                bUpdate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bUpdateActionPerformed(evt);
                        }
                });

                genderL.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                genderL.setText("Gender:");

                noteL.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                noteL.setText("Notes:");

                noteTxt.setColumns(20);
                noteTxt.setRows(5);
                jScrollPane2.setViewportView(noteTxt);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup().addContainerGap()
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jScrollPane1)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(speciesL)
                                                                                                                                .addComponent(breedL))
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(breedTxt)
                                                                                                                                .addComponent(speciesTxt)))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(genderL)
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addComponent(genderTxt,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                99,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                                .addComponent(bdayTxt,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                93,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(bdayL)
                                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(nameL)
                                                                                                                .addGap(32, 32, 32)
                                                                                                                .addComponent(nameTxt)))
                                                                                .addGap(33, 33, 33)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(noteL)
                                                                                                                .addGap(234, 234,
                                                                                                                                234))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jScrollPane2)
                                                                                                                .addGap(18, 18, 18)))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                91,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(96, 96, 96))
                                                                                                .addComponent(jLabel2,
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(bDelete,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                100,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(bAdd,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                100,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(bUpdate,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                100,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGap(88, 88, 88)))))
                                                .addContainerGap()));
                jPanel1Layout.setVerticalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                63,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel2)
                                                                                .addGap(67, 67, 67).addComponent(bAdd)
                                                                                .addGap(40, 40, 40)
                                                                                .addComponent(bDelete)
                                                                                .addGap(30, 30, 30)
                                                                                .addComponent(bUpdate))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(nameL)
                                                                                                                                .addComponent(nameTxt,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGap(38, 38, 38)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(speciesL)
                                                                                                                                .addComponent(speciesTxt,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGap(38, 38, 38)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(breedTxt,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(breedL))
                                                                                                                .addGap(38, 38, 38)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(bdayTxt,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                28,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(bdayL))
                                                                                                                .addGap(31, 31, 31)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(genderTxt,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(genderL)))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                .addComponent(noteL)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(jScrollPane2,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                239,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29,
                                                                Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap()));

                dateL.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
                dateL.setText("Date:");

                dateTxt.setEditable(false);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup().addComponent(bBack,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(dateL)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(dateTxt,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                80,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap()));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(bBack).addComponent(dateL).addComponent(dateTxt,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap()));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        ////////////////////////////////////////////////////////////////////////////////
        private void emplJtable() {

                // create JFrame and JTable
                JFrame frame = new JFrame();
                JTable table = new JTable();

                // create a table model and set a Column Identifiers to this model
                Object[] columns = { "Id", "First Name", "Last Name", "Age" };
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnIdentifiers(columns);

                // set the model to the table
                table.setModel(model);

                // Change A JTable Background Color, Font Size, Font Color, Row Height
                table.setBackground(Color.LIGHT_GRAY);
                table.setForeground(Color.black);
                Font font = new Font("", 1, 22);
                table.setFont(font);
                table.setRowHeight(30);

                // create JTextFields
                JTextField textId = new JTextField();
                JTextField textFname = new JTextField();
                JTextField textLname = new JTextField();
                JTextField textAge = new JTextField();

                // create JButtons
                JButton btnAdd = new JButton("Add");
                JButton btnDelete = new JButton("Delete");
                JButton btnUpdate = new JButton("Update");

                textId.setBounds(20, 220, 100, 25);
                textFname.setBounds(20, 250, 100, 25);
                textLname.setBounds(20, 280, 100, 25);
                textAge.setBounds(20, 310, 100, 25);

                btnAdd.setBounds(150, 220, 100, 25);
                btnUpdate.setBounds(150, 265, 100, 25);
                btnDelete.setBounds(150, 310, 100, 25);

                // create JScrollPane
                JScrollPane pane = new JScrollPane(table);
                pane.setBounds(0, 0, 880, 200);

                frame.setLayout(null);

                frame.add(pane);

                // add JTextFields to the jframe
                frame.add(textId);
                frame.add(textFname);
                frame.add(textLname);
                frame.add(textAge);

                // add JButtons to the jframe
                frame.add(btnAdd);
                frame.add(btnDelete);
                frame.add(btnUpdate);

                // create an array of objects to set the row data
                Object[] row = new Object[4];

                // button add row
                btnAdd.addActionListener(new ActionListener() {

                        @Override
                        public void actionPerformed(ActionEvent e) {

                                row[0] = textId.getText();
                                row[1] = textFname.getText();
                                row[2] = textLname.getText();
                                row[3] = textAge.getText();

                                // add row to the model
                                model.addRow(row);
                        }
                });

                // button remove row
                btnDelete.addActionListener(new ActionListener() {

                        @Override
                        public void actionPerformed(ActionEvent e) {

                                // i = the index of the selected row
                                int i = table.getSelectedRow();
                                if (i >= 0) {
                                        // remove a row from jtable
                                        model.removeRow(i);
                                } else {
                                        System.out.println("Delete Error");
                                }
                        }
                });

                // get selected row data From table to textfields
                table.addMouseListener(new MouseAdapter() {

                        @Override
                        public void mouseClicked(MouseEvent e) {

                                // i = the index of the selected row
                                int i = table.getSelectedRow();

                                textId.setText(model.getValueAt(i, 0).toString());
                                textFname.setText(model.getValueAt(i, 1).toString());
                                textLname.setText(model.getValueAt(i, 2).toString());
                                textAge.setText(model.getValueAt(i, 3).toString());
                        }
                });

                // button update row
                btnUpdate.addActionListener(new ActionListener() {

                        @Override
                        public void actionPerformed(ActionEvent e) {

                                // i = the index of the selected row
                                int i = table.getSelectedRow();

                                if (i >= 0) {
                                        model.setValueAt(textId.getText(), i, 0);
                                        model.setValueAt(textFname.getText(), i, 1);
                                        model.setValueAt(textLname.getText(), i, 2);
                                        model.setValueAt(textAge.getText(), i, 3);
                                } else {
                                        System.out.println("Update Error");
                                }
                        }
                });

                frame.setSize(900, 400);
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setVisible(true);

                ////////////////////////////////////////////////////////////////////////
        }

        // BACK BOTTON
        private void bBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bBackActionPerformed
                // TODO add your handling code here:
                this.setVisible(false);
                new vetClient().setVisible(true);
        }// GEN-LAST:event_bBackActionPerformed

        // ADD BOTTON
        private void bAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bAddActionPerformed
                // TODO add your handling code here:
                Pet pet = new Pet();
                pet.setBirthday(bdayTxt.getText());
                pet.setBreed(breedTxt.getText());
                pet.setComments(noteTxt.getText());
                pet.setCustomerID(customer.getCustomerID());
                pet.setGender(genderTxt.getText());
                pet.setName(nameTxt.getText());
                pet.setSpecies(speciesTxt.getText());
                pet.setPetID(DatabaseManager.addPet(pet));
                customer.addPet(pet);

                model.insertRow(model.getRowCount(), new Object[] { pet.getName(), pet.getSpecies(), pet.getBreed(),
                                pet.getBirthday(), pet.getGender() });
                System.out.println(customer);

        }// GEN-LAST:event_bAddActionPerformed

        // DELETE BOTTON
        private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bDeleteActionPerformed
                // TODO add your handling code here:
                // check for selected row first
                if (petTable.getSelectedRowCount() == 1) {
                        String name = (String) model.getValueAt(petTable.getSelectedRow(), 0);
                        String species = (String) model.getValueAt(petTable.getSelectedRow(), 1);
                        String breed = (String) model.getValueAt(petTable.getSelectedRow(), 2);
                        String birthday = (String) model.getValueAt(petTable.getSelectedRow(), 3);
                        String gender = (String) model.getValueAt(petTable.getSelectedRow(), 4);

                        ArrayList<Pet> pets = customer.getPets();
                        Pet pet = null;
                        for (int i = 0; i < pets.size(); i++)
                                if (pets.get(i).getName() == name && pets.get(i).getSpecies() == species
                                                && pets.get(i).getBreed() == breed
                                                && pets.get(i).getBirthday() == birthday
                                                && pets.get(i).getGender() == gender)
                                        pet = pets.get(i);

                        if (pet != null) {
                                customer.removePet(pet.getPetID());
                                DatabaseManager.removePet(pet.getPetID());

                                model.removeRow(petTable.getSelectedRow());

                                nameTxt.setText("");
                                speciesTxt.setText("");
                                breedTxt.setText("");
                                bdayTxt.setText("");
                                genderTxt.setText("");
                                noteTxt.setText("");
                        } else {
                                System.out.println("error delete");
                        }
                        System.out.println(customer);
                }
        }// GEN-LAST:event_bDeleteActionPerformed

        // UPSATE BOTTON
        private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bUpdateActionPerformed
                // // TODO add your handling code here:

                if (petTable.getSelectedRowCount() == 1) {
                        String oldName = (String) model.getValueAt(petTable.getSelectedRow(), 0);
                        String oldSpecies = (String) model.getValueAt(petTable.getSelectedRow(), 1);
                        String oldBreed = (String) model.getValueAt(petTable.getSelectedRow(), 2);
                        String oldBirthday = (String) model.getValueAt(petTable.getSelectedRow(), 3);
                        String oldGender = (String) model.getValueAt(petTable.getSelectedRow(), 4);

                        ArrayList<Pet> pets = customer.getPets();
                        Pet pet = null;
                        for (int i = 0; i < pets.size(); i++)
                                if (pets.get(i).getName() == oldName && pets.get(i).getSpecies() == oldSpecies
                                                && pets.get(i).getBreed() == oldBreed
                                                && pets.get(i).getBirthday() == oldBirthday
                                                && pets.get(i).getGender() == oldGender)
                                        pet = pets.get(i);

                        if (pet != null) {
                                String name = nameTxt.getText();
                                String species = speciesTxt.getText();
                                String breed = breedTxt.getText();
                                String birthday = bdayTxt.getText();
                                String gender = genderTxt.getText();

                                Pet newPet = new Pet();
                                newPet.setName(name);
                                newPet.setSpecies(species);
                                newPet.setBreed(breed);
                                newPet.setBirthday(birthday);
                                newPet.setGender(gender);
                                newPet.setComments(noteTxt.getText());

                                customer.updatePet(pet.getPetID(), newPet);
                                CustomerManager cm = new CustomerManager();
                                customer = cm.getCustomer(customer.getCustomerID());

                                model.setValueAt(name, petTable.getSelectedRow(), 0);
                                model.setValueAt(species, petTable.getSelectedRow(), 1);
                                model.setValueAt(breed, petTable.getSelectedRow(), 2);
                                model.setValueAt(birthday, petTable.getSelectedRow(), 3);
                                model.setValueAt(gender, petTable.getSelectedRow(), 4);
                        } else {
                                System.out.println("error update");
                        }
                        System.out.println(customer);
                }
        }// GEN-LAST:event_bUpdateActionPerformed

        // CLICK TABLE LINE AND ADD IT BACK TO TXT BOXES
        private void petTableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_petTableMouseClicked
                // TODO add your handling code here:
                // System.out.println("Clicked");

                String name = (String) model.getValueAt(petTable.getSelectedRow(), 0);
                String species = (String) model.getValueAt(petTable.getSelectedRow(), 1);
                String breed = (String) model.getValueAt(petTable.getSelectedRow(), 2);
                String birthday = (String) model.getValueAt(petTable.getSelectedRow(), 3);
                String gender = (String) model.getValueAt(petTable.getSelectedRow(), 4);

                ArrayList<Pet> pets = customer.getPets();
                Pet pet = null;
                for (int i = 0; i < pets.size(); i++)
                        if (pets.get(i).getName() == name && pets.get(i).getSpecies() == species
                                        && pets.get(i).getBreed() == breed && pets.get(i).getBirthday() == birthday
                                        && pets.get(i).getGender() == gender)
                                pet = pets.get(i);
                if (pet != null) {
                        nameTxt.setText(pet.getName());
                        speciesTxt.setText(pet.getSpecies());
                        breedTxt.setText(pet.getBreed());
                        bdayTxt.setText(pet.getBirthday());
                        genderTxt.setText(pet.getGender());
                        noteTxt.setText(pet.getComments());
                }
                System.out.println(customer);

        }// GEN-LAST:event_petTableMouseClicked

        public void setCustomer(Customer customer) {
                this.customer = customer;
        }

        public void fillTable() {
                ArrayList<Pet> pets = customer.getPets();
                for (int i = 0; i < pets.size(); i++) {
                        Pet pet = pets.get(i);
                        model.insertRow(model.getRowCount(), new Object[] { pet.getName(), pet.getSpecies(),
                                        pet.getBreed(), pet.getBirthday(), pet.getGender() });
                }
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton bAdd;
        private javax.swing.JButton bBack;
        private javax.swing.JButton bDelete;
        private javax.swing.JButton bUpdate;
        private javax.swing.JLabel bdayL;
        private javax.swing.JTextField bdayTxt;
        private javax.swing.JLabel breedL;
        private javax.swing.JTextField breedTxt;
        private javax.swing.JLabel dateL;
        private javax.swing.JTextField dateTxt;
        private javax.swing.JLabel genderL;
        private javax.swing.JTextField genderTxt;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JLabel nameL;
        private javax.swing.JTextField nameTxt;
        private javax.swing.JLabel noteL;
        private javax.swing.JTextArea noteTxt;
        private javax.swing.JTable petTable;
        private javax.swing.JLabel speciesL;
        private javax.swing.JTextField speciesTxt;
        private Customer customer;
        // End of variables declaration//GEN-END:variables
}