package System.GUI;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import System.API.*;

/**
 *
 * @author Jessica
 */
public class vetEmpl extends javax.swing.JFrame {

        DateFormat dateFormat = new SimpleDateFormat("MM/dd/YY");
        Date date = new Date();
        Calendar cal = Calendar.getInstance();
        DefaultTableModel model;

        /**
         * Creates new form vetEmpl
         */
        public vetEmpl() {
                initComponents();

                System.out.println("Starting Employee");

                model = (DefaultTableModel) emplTable.getModel();
                dateTxt.setText(" " + dateFormat.format(date));

                emplTable.setShowHorizontalLines(true);
                emplTable.setShowVerticalLines(true);

                fillFromDatabase();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                bBack = new javax.swing.JButton();
                jPanel1 = new javax.swing.JPanel();
                startDateL = new javax.swing.JLabel();
                firstNameL = new javax.swing.JLabel();
                lastNameL = new javax.swing.JLabel();
                phoneL = new javax.swing.JLabel();
                startDateTxt = new javax.swing.JTextField();
                firstNameTxt = new javax.swing.JTextField();
                lastNameTxt = new javax.swing.JTextField();
                phoneTxt = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                emplTable = new javax.swing.JTable();
                bAdd = new javax.swing.JButton();
                bDelete = new javax.swing.JButton();
                bUpdate = new javax.swing.JButton();
                idTxt = new javax.swing.JLabel();
                idL = new javax.swing.JLabel();
                hoursL = new javax.swing.JLabel();
                hoursTxt = new javax.swing.JTextField();
                dateL = new javax.swing.JLabel();
                dateTxt = new javax.swing.JTextField();

                em = new EmployeeManager();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Employee Management");

                bBack.setText("BACK");
                bBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bBackActionPerformed(evt);
                        }
                });

                jPanel1.setBackground(new java.awt.Color(167, 231, 225));

                startDateL.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                startDateL.setText("START DAY:");

                firstNameL.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                firstNameL.setText("FIRST NAME:");

                lastNameL.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                lastNameL.setText("LAST NAME:");

                phoneL.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                phoneL.setText("PHONE #:");

                jLabel1.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
                jLabel1.setText("Employee");

                jLabel2.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
                jLabel2.setText("Management");

                emplTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

                }, new String[] { "ID", "Name", "Last Name", "Phone Num.", "Start Date", "Hours" }) {
                        boolean[] canEdit = new boolean[] { false, false, false, false, false, false };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                emplTable.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                emplTableMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(emplTable);
                if (emplTable.getColumnModel().getColumnCount() > 0) {
                        emplTable.getColumnModel().getColumn(0).setResizable(false);
                        emplTable.getColumnModel().getColumn(1).setResizable(false);
                        emplTable.getColumnModel().getColumn(2).setResizable(false);
                        emplTable.getColumnModel().getColumn(3).setResizable(false);
                        emplTable.getColumnModel().getColumn(4).setResizable(false);
                        emplTable.getColumnModel().getColumn(5).setResizable(false);
                }

                bAdd.setText("ADD");
                bAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bAddActionPerformed(evt);
                        }
                });

                bDelete.setText("DELETE");
                bDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bDeleteActionPerformed(evt);
                        }
                });

                bUpdate.setText("UPDATE");
                bUpdate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bUpdateActionPerformed(evt);
                        }
                });

                idTxt.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                idTxt.setText("###");

                idL.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                idL.setText("ID:");

                hoursL.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                hoursL.setText("HOURS:");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(40, 40, 40)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(idL,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                30,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(idTxt,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                83,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(firstNameL)
                                                                                                                .addComponent(phoneL)
                                                                                                                .addComponent(hoursL,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                69,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(13, 13, 13)
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                .addComponent(hoursTxt)
                                                                                                                                                .addComponent(phoneTxt,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                120,
                                                                                                                                                                Short.MAX_VALUE)))
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(firstNameTxt)))
                                                                                                .addGap(58, 58, 58)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(startDateL)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(startDateTxt))
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(lastNameL)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(lastNameTxt,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                120,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(bDelete,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                100,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(bUpdate,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                100,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(bAdd,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                100,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(47, 47, 47))))
                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(565, 565, 565)
                                                .addComponent(jLabel1).addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(16, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jLabel2).addGap(32, 32, 32)));
                jPanel1Layout.setVerticalGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup().addContainerGap().addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2).addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(idTxt).addComponent(idL))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(105, 105,
                                                                                                                                105)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(hoursL)
                                                                                                                                .addComponent(hoursTxt,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(17, 17, 17)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(firstNameL)
                                                                                                                                .addComponent(firstNameTxt,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(lastNameL)
                                                                                                                                .addComponent(lastNameTxt,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(startDateL)
                                                                                                                                .addComponent(startDateTxt,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                28,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(phoneL)
                                                                                                                                .addComponent(phoneTxt,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                .addGap(21, 21, 21))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(bAdd).addGap(32, 32, 32)
                                                                                .addComponent(bDelete)
                                                                                .addGap(32, 32, 32)
                                                                                .addComponent(bUpdate)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));

                dateL.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
                dateL.setText("Date:");

                dateTxt.setEditable(false);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup().addComponent(bBack,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(dateL)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(dateTxt,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                80,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap()));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(bBack).addComponent(dateL).addComponent(dateTxt,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(20, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        ////////////////////////////////////////////////////////////////////////////////
        private void emplJtable() {

                // create JFrame and JTable
                JFrame frame = new JFrame();
                JTable table = new JTable();

                // create a table model and set a Column Identifiers to this model
                Object[] columns = { "Id", "First Name", "Last Name", "Age" };
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnIdentifiers(columns);

                // set the model to the table
                table.setModel(model);

                // Change A JTable Background Color, Font Size, Font Color, Row Height
                table.setBackground(Color.LIGHT_GRAY);
                table.setForeground(Color.black);
                Font font = new Font("", 1, 22);
                table.setFont(font);
                table.setRowHeight(30);

                // create JTextFields
                JTextField textId = new JTextField();
                JTextField textFname = new JTextField();
                JTextField textLname = new JTextField();
                JTextField textAge = new JTextField();

                // create JButtons
                JButton btnAdd = new JButton("Add");
                JButton btnDelete = new JButton("Delete");
                JButton btnUpdate = new JButton("Update");

                textId.setBounds(20, 220, 100, 25);
                textFname.setBounds(20, 250, 100, 25);
                textLname.setBounds(20, 280, 100, 25);
                textAge.setBounds(20, 310, 100, 25);

                btnAdd.setBounds(150, 220, 100, 25);
                btnUpdate.setBounds(150, 265, 100, 25);
                btnDelete.setBounds(150, 310, 100, 25);

                // create JScrollPane
                JScrollPane pane = new JScrollPane(table);
                pane.setBounds(0, 0, 880, 200);

                frame.setLayout(null);

                frame.add(pane);

                // add JTextFields to the jframe
                frame.add(textId);
                frame.add(textFname);
                frame.add(textLname);
                frame.add(textAge);

                // add JButtons to the jframe
                frame.add(btnAdd);
                frame.add(btnDelete);
                frame.add(btnUpdate);

                // create an array of objects to set the row data
                Object[] row = new Object[4];

                // button add row
                btnAdd.addActionListener(new ActionListener() {

                        @Override
                        public void actionPerformed(ActionEvent e) {

                                row[0] = textId.getText();
                                row[1] = textFname.getText();
                                row[2] = textLname.getText();
                                row[3] = textAge.getText();

                                // add row to the model
                                model.addRow(row);
                        }
                });

                // button remove row
                btnDelete.addActionListener(new ActionListener() {

                        @Override
                        public void actionPerformed(ActionEvent e) {

                                // i = the index of the selected row
                                int i = table.getSelectedRow();
                                if (i >= 0) {
                                        // remove a row from jtable
                                        model.removeRow(i);
                                } else {
                                        System.out.println("Delete Error");
                                }
                        }
                });

                // get selected row data From table to textfields
                table.addMouseListener(new MouseAdapter() {

                        @Override
                        public void mouseClicked(MouseEvent e) {

                                // i = the index of the selected row
                                int i = table.getSelectedRow();

                                textId.setText(model.getValueAt(i, 0).toString());
                                textFname.setText(model.getValueAt(i, 1).toString());
                                textLname.setText(model.getValueAt(i, 2).toString());
                                textAge.setText(model.getValueAt(i, 3).toString());
                        }
                });

                // button update row
                btnUpdate.addActionListener(new ActionListener() {

                        @Override
                        public void actionPerformed(ActionEvent e) {

                                // i = the index of the selected row
                                int i = table.getSelectedRow();

                                if (i >= 0) {
                                        model.setValueAt(textId.getText(), i, 0);
                                        model.setValueAt(textFname.getText(), i, 1);
                                        model.setValueAt(textLname.getText(), i, 2);
                                        model.setValueAt(textAge.getText(), i, 3);
                                } else {
                                        System.out.println("Update Error");
                                }
                        }
                });

                frame.setSize(900, 400);
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setVisible(true);

                ////////////////////////////////////////////////////////////////////////
        }

        // BACK BOTTON
        private void bBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bBackActionPerformed
                // TODO add your handling code here:
                this.setVisible(false);
                new vetView().setVisible(true);
        }// GEN-LAST:event_bBackActionPerformed

        // ADD BOTTON
        private void bAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bAddActionPerformed
                // TODO add your handling code here:
                Employee employee = new Employee();
                employee.setFirstName(firstNameTxt.getText());
                employee.setLastName(lastNameTxt.getText());
                employee.setPhoneNumber(phoneTxt.getText());
                employee.setStartDate(startDateTxt.getText());
                // check error
                employee.setWeeklyHours(Integer.parseInt(hoursTxt.getText()));
                employee.setScheduledHours(0);
                employee.setEmployeeID(em.addEmployee(employee));

                model.insertRow(model.getRowCount(),
                                new Object[] { employee.getEmployeeID(), employee.getFirstName(),
                                                employee.getLastName(), employee.getPhoneNumber(),
                                                employee.getStartDate(), employee.getWeeklyHours() });

        }// GEN-LAST:event_bAddActionPerformed

        // DELETE BOTTON
        private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bDeleteActionPerformed
                // TODO add your handling code here:
                // check for selected row first
                if (emplTable.getSelectedRowCount() == 1) {
                        int EID = (int) model.getValueAt(emplTable.getSelectedRow(), 0);
                        em.removeEmployee(EID);
                        model.removeRow(emplTable.getSelectedRow());

                        firstNameTxt.setText("");
                        lastNameTxt.setText("");
                        phoneTxt.setText("");
                        startDateTxt.setText("");
                        hoursTxt.setText("");
                }
        }// GEN-LAST:event_bDeleteActionPerformed

        // UPSATE BOTTON
        private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bUpdateActionPerformed
                // TODO add your handling code here:
                if (emplTable.getSelectedRowCount() == 1) {
                        int EID = (int) model.getValueAt(emplTable.getSelectedRow(), 0);
                        String fname = firstNameTxt.getText();
                        String lname = lastNameTxt.getText();
                        String phone = phoneTxt.getText();
                        String srtDate = startDateTxt.getText();
                        String hours = hoursTxt.getText();

                        Employee employee = new Employee(fname, lname, phone, srtDate, Integer.parseInt(hours), 0);

                        em.updateEmployee(EID, employee);

                        model.setValueAt(fname, emplTable.getSelectedRow(), 1);
                        model.setValueAt(lname, emplTable.getSelectedRow(), 2);
                        model.setValueAt(phone, emplTable.getSelectedRow(), 3);
                        model.setValueAt(srtDate, emplTable.getSelectedRow(), 4);
                        model.setValueAt(hours, emplTable.getSelectedRow(), 5);
                }
        }// GEN-LAST:event_bUpdateActionPerformed

        // CLICK TABLE LINE AND ADD IT BACK TO TXT BOXES
        private void emplTableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_emplTableMouseClicked
                // TODO add your handling code here:

                String fnameTbl = model.getValueAt(emplTable.getSelectedRow(), 1).toString();
                String lnameTbl = model.getValueAt(emplTable.getSelectedRow(), 2).toString();
                String phoneTbl = model.getValueAt(emplTable.getSelectedRow(), 3).toString();
                String srtDateTbl = model.getValueAt(emplTable.getSelectedRow(), 4).toString();
                String hoursTbl = model.getValueAt(emplTable.getSelectedRow(), 5).toString();

                firstNameTxt.setText(fnameTbl);
                lastNameTxt.setText(lnameTbl);
                phoneTxt.setText(phoneTbl);
                startDateTxt.setText(srtDateTbl);
                hoursTxt.setText(hoursTbl);
        }// GEN-LAST:event_emplTableMouseClicked

        public void fillFromDatabase() {
                ArrayList<Employee> employees = em.getEmployees();
                for (int i = 0; i < employees.size(); i++)
                        model.insertRow(model.getRowCount(), new Object[] { employees.get(i).getEmployeeID(),
                                        employees.get(i).getFirstName(), employees.get(i).getLastName(),
                                        employees.get(i).getPhoneNumber(), employees.get(i).getStartDate(),
                                        employees.get(i).getWeeklyHours() });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton bAdd;
        private javax.swing.JButton bBack;
        private javax.swing.JButton bDelete;
        private javax.swing.JButton bUpdate;
        private javax.swing.JLabel dateL;
        private javax.swing.JTextField dateTxt;
        private javax.swing.JTable emplTable;
        private javax.swing.JLabel firstNameL;
        private javax.swing.JTextField firstNameTxt;
        private javax.swing.JLabel hoursL;
        private javax.swing.JTextField hoursTxt;
        private javax.swing.JLabel idL;
        private javax.swing.JLabel idTxt;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lastNameL;
        private javax.swing.JTextField lastNameTxt;
        private javax.swing.JLabel phoneL;
        private javax.swing.JTextField phoneTxt;
        private javax.swing.JLabel startDateL;
        private javax.swing.JTextField startDateTxt;
        private EmployeeManager em;
        // End of variables declaration//GEN-END:variables
}
