package System.GUI;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

import System.API.*;
import System.DatabaseSystems.DatabaseManager;
import System.SchedulerSystem.Scheduler;

/**
 *
 * @author Jessica
 */
public class vetView extends javax.swing.JFrame {

        DateFormat dateFormat = new SimpleDateFormat("MM/dd/YY");
        Date date = new Date();
        Calendar cal = Calendar.getInstance();
        DefaultTableModel model;

        /**
         * Creates new form vetView
         */
        public vetView() {
                initComponents();

                /* model = (DefaultTableModel) scheTable.getModel(); */
                dateTxt.setText(" " + dateFormat.format(date));

                /* Table borders */

                jTable1.setShowHorizontalLines(true);
                jTable1.setShowVerticalLines(true);
                jTable1.setRowHeight(30);
                jTable2.setShowHorizontalLines(true);
                jTable2.setShowVerticalLines(true);
                jTable2.setRowHeight(30);
                jTable3.setShowHorizontalLines(true);
                jTable3.setShowVerticalLines(true);
                jTable3.setRowHeight(30);

                loadSchedule();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jButton4 = new javax.swing.JButton();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable2 = new javax.swing.JTable();
                jScrollPane3 = new javax.swing.JScrollPane();
                jTable3 = new javax.swing.JTable();
                jLabel2 = new javax.swing.JLabel();
                jButton3 = new javax.swing.JButton();
                dateL = new javax.swing.JLabel();
                dateTxt = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(64, 147, 240));

                jButton1.setBackground(new java.awt.Color(209, 219, 221));
                jButton1.setText("BACK");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButton2.setText("Clients");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                jPanel2.setBackground(new java.awt.Color(64, 147, 240));

                jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(254, 254, 254));
                jLabel1.setText("SCHEDULE");

                jButton4.setText("Run Calendar");
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                        }
                });

                jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTable1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] { { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null } },
                                new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",
                                                "Sunday" }));
                jTable1.setToolTipText("");
                jTable1.setColumnSelectionAllowed(true);
                jTable1.getTableHeader().setReorderingAllowed(false);
                jScrollPane1.setViewportView(jTable1);
                jTable1.getColumnModel().getSelectionModel()
                                .setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
                if (jTable1.getColumnModel().getColumnCount() > 0) {
                        jTable1.getColumnModel().getColumn(0).setResizable(false);
                        jTable1.getColumnModel().getColumn(1).setResizable(false);
                        jTable1.getColumnModel().getColumn(2).setResizable(false);
                        jTable1.getColumnModel().getColumn(3).setResizable(false);
                        jTable1.getColumnModel().getColumn(4).setResizable(false);
                        jTable1.getColumnModel().getColumn(5).setResizable(false);
                        jTable1.getColumnModel().getColumn(6).setResizable(false);
                }

                jTabbedPane1.addTab("Week 1", jScrollPane1);

                jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTable2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                jTable2.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] { { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null } },
                                new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",
                                                "Sunday" }));
                jTable2.getTableHeader().setReorderingAllowed(false);
                jScrollPane2.setViewportView(jTable2);
                jTable2.getColumnModel().getSelectionModel()
                                .setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                if (jTable2.getColumnModel().getColumnCount() > 0) {
                        jTable2.getColumnModel().getColumn(0).setResizable(false);
                        jTable2.getColumnModel().getColumn(1).setResizable(false);
                        jTable2.getColumnModel().getColumn(2).setResizable(false);
                        jTable2.getColumnModel().getColumn(3).setResizable(false);
                        jTable2.getColumnModel().getColumn(4).setResizable(false);
                        jTable2.getColumnModel().getColumn(5).setResizable(false);
                        jTable2.getColumnModel().getColumn(6).setResizable(false);
                }

                jTabbedPane1.addTab("Week 2", jScrollPane2);

                jTable3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jTable3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
                jTable3.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] { { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null } },
                                new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",
                                                "Sunday" }));
                jTable3.getTableHeader().setReorderingAllowed(false);
                jScrollPane3.setViewportView(jTable3);
                jTable3.getColumnModel().getSelectionModel()
                                .setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                if (jTable3.getColumnModel().getColumnCount() > 0) {
                        jTable3.getColumnModel().getColumn(0).setResizable(false);
                        jTable3.getColumnModel().getColumn(1).setResizable(false);
                        jTable3.getColumnModel().getColumn(2).setResizable(false);
                        jTable3.getColumnModel().getColumn(3).setResizable(false);
                        jTable3.getColumnModel().getColumn(4).setResizable(false);
                        jTable3.getColumnModel().getColumn(5).setResizable(false);
                        jTable3.getColumnModel().getColumn(6).setResizable(false);
                }

                jTabbedPane1.addTab("Week 3", jScrollPane3);

                jLabel2.setIcon(new javax.swing.ImageIcon("CS4398/System/GUI/PHOTOS/pets_row(1).png")); // NOI18N

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup().addGap(22, 22, 22)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel1)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                120,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jTabbedPane1)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(26, Short.MAX_VALUE)
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                738,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addGap(46, 46, 46)
                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel1).addComponent(jButton4))
                                                .addGap(30, 30, 30)
                                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 158,
                                                                Short.MAX_VALUE)
                                                .addContainerGap()));

                jButton3.setText("Employees");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                dateL.setText("Date:");

                dateTxt.setEditable(false);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup().addComponent(jPanel2,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addContainerGap())
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButton1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(dateL,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                47,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(dateTxt,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                80,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(54, 54, 54))))
                                .addGroup(layout.createSequentialGroup().addGap(189, 189, 189)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(178, 178, 178)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jButton1).addComponent(dateL).addComponent(dateTxt,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jButton3).addComponent(jButton2))
                                                .addContainerGap()));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        // BACK BOTTON
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
                this.setVisible(false);
                new NewJFrame().setVisible(true);
        }// GEN-LAST:event_jButton1ActionPerformed

        // CLIENT BOTTON
        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
                // TODO add your handling code here:
                this.setVisible(false);
                new vetClient().setVisible(true);
        }// GEN-LAST:event_jButton2ActionPerformed

        // EMPLOYEE BOTTON
        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
                // TODO add your handling code here:
                this.setVisible(false);
                new vetEmpl().setVisible(true);
        }// GEN-LAST:event_jButton3ActionPerformed

        // SCHEDULE BOTTON
        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
                // TODO add your handling code here:

                Runnable r1 = new Runnable() {
                        public void run() {
                                EmployeeManager em = new EmployeeManager();
                                Scheduler scheduler = new Scheduler();
                                ArrayList<ArrayList<Employee>> employees = scheduler.populateWeek(em.getEmployees());
                                DatabaseManager.deleteWeek();
                                DatabaseManager.addWeek(employees, 0);

                                for (int i = 0; i < employees.size(); i++) {
                                        ArrayList<Employee> day = employees.get(i);
                                        for (int j = 0; j < day.size(); j++) {
                                                jTable1.setValueAt(day.get(j).getFirstName(), j, i);
                                        }
                                }

                                employees = scheduler.populateWeek(em.getEmployees());
                                DatabaseManager.addWeek(employees, 1);

                                for (int i = 0; i < employees.size(); i++) {
                                        ArrayList<Employee> day = employees.get(i);
                                        for (int j = 0; j < day.size(); j++) {
                                                jTable2.setValueAt(day.get(j).getFirstName(), j, i);
                                        }
                                }

                                employees = scheduler.populateWeek(em.getEmployees());
                                DatabaseManager.addWeek(employees, 2);

                                for (int i = 0; i < employees.size(); i++) {
                                        ArrayList<Employee> day = employees.get(i);
                                        for (int j = 0; j < day.size(); j++) {
                                                jTable3.setValueAt(day.get(j).getFirstName(), j, i);
                                        }
                                }
                        }

                };

                new Thread(r1).start();
        }// GEN-LAST:event_jButton4ActionPerformed

        public void loadSchedule() {
                Runnable r1 = new Runnable() {
                        public void run() {
                                ArrayList<ArrayList<Employee>> employees = DatabaseManager.getEmployeeSchedule(0);
                                for (int i = 0; i < employees.size(); i++) {
                                        ArrayList<Employee> day = employees.get(i);
                                        for (int j = 0; j < day.size(); j++) {
                                                jTable1.setValueAt(day.get(j).getFirstName(), j, i);
                                        }
                                }
                        }
                };

                Runnable r2 = new Runnable() {
                        public void run() {
                                ArrayList<ArrayList<Employee>> employees = DatabaseManager.getEmployeeSchedule(1);
                                for (int i = 0; i < employees.size(); i++) {
                                        ArrayList<Employee> day = employees.get(i);
                                        for (int j = 0; j < day.size(); j++) {
                                                jTable2.setValueAt(day.get(j).getFirstName(), j, i);
                                        }
                                }
                        }
                };

                Runnable r3 = new Runnable() {
                        public void run() {
                                ArrayList<ArrayList<Employee>> employees = DatabaseManager.getEmployeeSchedule(2);
                                for (int i = 0; i < employees.size(); i++) {
                                        ArrayList<Employee> day = employees.get(i);
                                        for (int j = 0; j < day.size(); j++) {
                                                jTable3.setValueAt(day.get(j).getFirstName(), j, i);
                                        }
                                }
                        }
                };

                new Thread(r1).start();
                new Thread(r2).start();
                new Thread(r3).start();
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel dateL;
        private javax.swing.JTextField dateTxt;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JTable jTable2;
        private javax.swing.JTable jTable3;
        // End of variables declaration//GEN-END:variables
}
